[tox]
envlist = py312, lint, format, check_files

[testenv]
deps =
    pytest
    -rrequirements.txt
commands =
    pytest --maxfail=5 --disable-warnings Chatbot/
    pytest Test/

[testenv:lint]
description = Lint the code with flake8
deps =
    flake8
commands =
    flake8 Chatbot/

[testenv:format]
description = Format code with black and isort
deps =
    black
    isort
commands =
    black Chatbot/
    isort Chatbot/

[testenv:check_files]
description = Check for empty or corrupted files
; deps = os, pycompile, isEmpty
commands =
    python isEmpty.py





